module.exports = {
  SUPER_ADMIN: [
    "PROPERTY_APPROVE",
    "PROPERTY_REJECT",
    "PROPERTY_BLOCK",
    "PROPERTY_DELETE",
    "PROPERTY_RESTORE",
    "PREMIUM_GRANT",
    "PREMIUM_REMOVE",
    "VIEW_LEADS",
    "UPDATE_LEADS",
    "VIEW_AUDIT_LOGS",
    "MANAGE_ADMINS"
  ],

  ADMIN: [
    "PROPERTY_APPROVE",
    "PROPERTY_REJECT",
    "PROPERTY_BLOCK",
    "PREMIUM_GRANT",
    "PREMIUM_REMOVE",
    "VIEW_LEADS",
    "UPDATE_LEADS"
  ],

  MODERATOR: [
    "PROPERTY_APPROVE",
    "PROPERTY_REJECT",
    "PROPERTY_BLOCK",
    "VIEW_LEADS"
  ],

  SUPPORT: [
    "VIEW_LEADS"
  ]
};
